package models

type PermissionDescriptor struct {
	Name        string
	Description string
}

func PermissionDescriptors() []PermissionDescriptor {
	return []PermissionDescriptor{
		{"warehouse.view_overview", "Dashboard / bootstrap"},
		{"warehouse.view_location", "View facilities, zones, bins"},
		{"warehouse.add_location", "Create facilities, zones, bins"},
		{"warehouse.change_location", "Update facilities, zones, bins"},
		{"warehouse.view_item", "View item master"},
		{"warehouse.add_item", "Create items"},
		{"warehouse.change_item", "Update items"},
		{"warehouse.view_stock", "View balances and low stock"},
		{"warehouse.view_receipt", "View receipts"},
		{"warehouse.add_receipt", "Create receipts"},
		{"warehouse.post_receipt", "Post receipts to stock"},
		{"warehouse.view_issue", "View issues"},
		{"warehouse.add_issue", "Create issues"},
		{"warehouse.post_issue", "Post issues from stock"},
		{"warehouse.issue_consumable", "Issue consumables to departments"},
		{"warehouse.production_consume", "Production RM consumption"},
		{"warehouse.production_output", "Production FG output"},
		{"warehouse.add_transfer", "Create bin transfers"},
		{"warehouse.adjust_stock", "Stock adjustments"},
		{"warehouse.cycle_count", "Cycle count adjustments"},
		{"warehouse.view_asset", "View equipment assets"},
		{"warehouse.add_asset", "Register equipment assets"},
		{"warehouse.checkin_asset", "Check in equipment to bin"},
		{"warehouse.checkout_asset", "Check out equipment custody"},
		{"warehouse.dispose_asset", "Dispose / retire equipment assets"},
		{"warehouse.approve_disposal_tier1", "Approve asset disposal at tier 1 (lowest value band)"},
		{"warehouse.approve_disposal_tier2", "Approve asset disposal at tier 2 (mid value band)"},
		{"warehouse.approve_disposal_tier3", "Approve asset disposal at tier 3 (highest value band)"},
		{"warehouse.add_pick", "Create pick lists"},
		{"warehouse.confirm_pick", "Confirm pick lists"},
		{"warehouse.add_pack", "Create pack sessions"},
		{"warehouse.view_threshold", "View stock-alert thresholds"},
		{"warehouse.add_threshold", "Create stock-alert thresholds"},
		{"warehouse.change_threshold", "Update / delete stock-alert thresholds"},
		{"warehouse.view_return", "View stock returns"},
		{"warehouse.add_return", "Log stock returns"},
		{"warehouse.change_return", "Update / delete stock returns"},
		{"warehouse.view_gatepass", "View gate passes"},
		{"warehouse.add_gatepass", "Issue gate passes"},
		{"warehouse.change_gatepass", "Update / return / delete gate passes"},
		{"warehouse.view_warranty", "View equipment warranties"},
		{"warehouse.add_warranty", "Create equipment warranties"},
		{"warehouse.change_warranty", "Update / delete equipment warranties"},
		{"warehouse.view_event", "View event / furniture requests"},
		{"warehouse.add_event", "Create event / furniture requests"},
		{"warehouse.change_event", "Update / delete event / furniture requests"},
		{"warehouse.view_tool", "View small-tools register"},
		{"warehouse.add_tool", "Tag / register small tools"},
		{"warehouse.change_tool", "Update / delete small-tools records"},
		{"warehouse.admin.read", "Staff audit and monitoring"},
	}
}
