package models

type PermissionDescriptor struct {
	Name        string
	Description string
}

func PermissionDescriptors() []PermissionDescriptor {
	return []PermissionDescriptor{
		{"warehouse.view_overview", "Dashboard / bootstrap"},
		{"warehouse.view_location", "View facilities, zones, bins"},
		{"warehouse.add_location", "Create facilities, zones, bins"},
		{"warehouse.change_location", "Update facilities, zones, bins"},
		{"warehouse.view_item", "View item master"},
		{"warehouse.add_item", "Create items"},
		{"warehouse.change_item", "Update items"},
		{"warehouse.view_stock", "View balances and low stock"},
		{"warehouse.view_receipt", "View receipts"},
		{"warehouse.add_receipt", "Create receipts"},
		{"warehouse.post_receipt", "Post receipts to stock"},
		{"warehouse.view_issue", "View issues"},
		{"warehouse.add_issue", "Create issues"},
		{"warehouse.post_issue", "Post issues from stock"},
		{"warehouse.issue_consumable", "Issue consumables to departments"},
		{"warehouse.production_consume", "Production RM consumption"},
		{"warehouse.production_output", "Production FG output"},
		{"warehouse.view_transfer", "View facility transfers"},
		{"warehouse.add_transfer", "Create bin transfers"},
		{"warehouse.adjust_stock", "Stock adjustments"},
		{"warehouse.cycle_count", "Cycle count adjustments"},
		{"warehouse.view_asset", "View equipment assets"},
		{"warehouse.add_asset", "Register equipment assets"},
		{"warehouse.checkin_asset", "Check in equipment to bin"},
		{"warehouse.checkout_asset", "Check out equipment custody"},
		{"warehouse.dispose_asset", "Dispose / retire equipment assets"},
		{"warehouse.approve_disposal_tier1", "Approve asset disposal at tier 1 (lowest value band)"},
		{"warehouse.approve_disposal_tier2", "Approve asset disposal at tier 2 (mid value band)"},
		{"warehouse.approve_disposal_tier3", "Approve asset disposal at tier 3 (highest value band)"},
		{"warehouse.add_pick", "Create pick lists"},
		{"warehouse.confirm_pick", "Confirm pick lists"},
		{"warehouse.add_pack", "Create pack sessions"},
		{"warehouse.view_pack", "View pack sessions"},
		{"warehouse.view_threshold", "View stock-alert thresholds"},
		{"warehouse.add_threshold", "Create stock-alert thresholds"},
		{"warehouse.change_threshold", "Update / delete stock-alert thresholds"},
		{"warehouse.view_return", "View stock returns"},
		{"warehouse.add_return", "Log stock returns"},
		{"warehouse.change_return", "Update / delete stock returns"},
		{"warehouse.view_gatepass", "View gate passes"},
		{"warehouse.add_gatepass", "Issue gate passes"},
		{"warehouse.change_gatepass", "Update / return / delete gate passes"},
		{"warehouse.view_warranty", "View equipment warranties"},
		{"warehouse.add_warranty", "Create equipment warranties"},
		{"warehouse.change_warranty", "Update / delete equipment warranties"},
		{"warehouse.view_event", "View event / furniture requests"},
		{"warehouse.add_event", "Create event / furniture requests"},
		{"warehouse.change_event", "Update / delete event / furniture requests"},
		{"warehouse.view_tool", "View small-tools register"},
		{"warehouse.add_tool", "Tag / register small tools"},
		{"warehouse.change_tool", "Update / delete small-tools records"},
		{"warehouse.admin.read", "Staff audit and monitoring"},

		// Execution layer: unit conversion, directed putaway, replenishment,
		// controlled counting, handling units, and RF scanning.
		{"warehouse.view_uom", "View item unit-of-measure conversions"},
		{"warehouse.change_uom", "Define / remove item unit-of-measure conversions"},
		{"warehouse.view_putaway", "View putaway rules and suggestions"},
		{"warehouse.change_putaway", "Create / update / delete putaway rules"},
		{"warehouse.view_replen", "View replenishment levels and tasks"},
		{"warehouse.change_replen", "Create / update / delete replenishment levels"},
		{"warehouse.add_replen_task", "Raise replenishment tasks"},
		{"warehouse.complete_replen", "Complete / cancel replenishment tasks"},
		{"warehouse.view_count", "View count tasks and count sheets"},
		{"warehouse.add_count", "Create count tasks"},
		{"warehouse.perform_count", "Record counted quantities"},
		{"warehouse.approve_count", "Approve a count and post its variances"},
		{"warehouse.classify_abc", "Run ABC classification over items"},
		{"warehouse.view_hu", "View handling units (licence plates)"},
		{"warehouse.add_hu", "Create handling units"},
		{"warehouse.change_hu", "Load, move, nest, and close handling units"},
		{"warehouse.view_barcode", "View the barcode registry"},
		{"warehouse.change_barcode", "Register / remove barcodes"},
		{"warehouse.scan", "Use the RF scanning endpoints"},
		{"warehouse.view_slip", "View gate passes and handover slips"},
		{"warehouse.add_slip", "Raise gate passes and handover slips"},
		{"warehouse.authorize_slip", "Authorise or reject a gate pass / handover slip"},
		{"warehouse.verify_slip", "Verify and release slips at the gate (security)"},
		{"warehouse.change_slip", "Book returns, close and cancel slips"},
	}
}
