package slips

import (
	"fmt"
	"html/template"
	"strings"
	"time"

	"iag-warehouse/backend/internal/models"
)

// The printed slip.
//
// This is the artefact the whole module exists to produce: one sheet of paper a
// driver hands to a guard. It is deliberately self-contained — inline CSS, an
// inline SVG barcode, no external anything — because it has to survive being
// opened on a depot PC with no internet and printed by whatever is attached to
// it.
//
// Two things on the page matter more than the rest: the barcode, so the guard
// can verify rather than believe, and the returns block, so equipment that is
// supposed to come back is visibly supposed to come back.

type PrintOptions struct {
	// OrgName is printed as the issuing organisation.
	OrgName string
	// VerifyURL, when set, is shown under the barcode as the address a guard's
	// terminal resolves the token at.
	VerifyURL string
}

var slipTemplate = template.Must(template.New("slip").Funcs(template.FuncMap{
	"date": func(t *time.Time) string {
		if t == nil {
			return "—"
		}
		return t.Format("2 Jan 2006")
	},
	"datetime": func(t *time.Time) string {
		if t == nil {
			return "—"
		}
		return t.Format("2 Jan 2006 15:04")
	},
	"qty": func(f float64) string {
		return strings.TrimSuffix(strings.TrimRight(fmt.Sprintf("%.3f", f), "0"), ".")
	},
	"dash": func(s string) string {
		if strings.TrimSpace(s) == "" {
			return "—"
		}
		return s
	},
	"svg": func(s string) template.HTML { return template.HTML(s) }, // #nosec G203 -- generated by Barcode39SVG, not user input
}).Parse(slipHTML))

// Render produces the printable HTML for a slip.
func Render(slip models.Slip, opts PrintOptions) (string, error) {
	title := "CARGO GATE PASS"
	if slip.SlipType == models.SlipEquipmentHandover {
		title = "EQUIPMENT HANDOVER SLIP"
	}
	slipNo := "DRAFT — NOT VALID"
	if slip.SlipNo != nil {
		slipNo = *slip.SlipNo
	}

	// A draft has no token and must not look like it does. The barcode is only
	// rendered for a slip that has actually been authorised.
	barcode := ""
	if slip.VerifyToken != nil && *slip.VerifyToken != "" {
		barcode = Barcode39SVG(*slip.VerifyToken)
	}

	data := struct {
		models.Slip
		Title     string
		SlipNoStr string
		Barcode   string
		OrgName   string
		VerifyURL string
		IsCargo   bool
		PrintedAt string
	}{
		Slip:      slip,
		Title:     title,
		SlipNoStr: slipNo,
		Barcode:   barcode,
		OrgName:   orDefault(opts.OrgName, "Inspire Africa Group"),
		VerifyURL: opts.VerifyURL,
		IsCargo:   slip.SlipType == models.SlipCargoGatePass,
		PrintedAt: time.Now().Format("2 Jan 2006 15:04"),
	}

	var sb strings.Builder
	if err := slipTemplate.Execute(&sb, data); err != nil {
		return "", err
	}
	return sb.String(), nil
}

func orDefault(s, def string) string {
	if strings.TrimSpace(s) == "" {
		return def
	}
	return s
}

const slipHTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>{{.Title}} {{.SlipNoStr}}</title>
<style>
  @page { size: A5 landscape; margin: 10mm; }
  * { box-sizing: border-box; }
  body { font: 12px/1.45 "Helvetica Neue", Arial, sans-serif; color: #111; margin: 0; padding: 16px; background: #fff; }
  .sheet { max-width: 800px; margin: 0 auto; border: 2px solid #111; padding: 16px; }
  header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #111; padding-bottom: 10px; }
  .org { font-size: 15px; font-weight: 700; letter-spacing: .04em; }
  .title { font-size: 17px; font-weight: 800; letter-spacing: .08em; }
  .no { font-family: "SFMono-Regular", Consolas, monospace; font-size: 16px; font-weight: 700; }
  .status { display: inline-block; padding: 2px 8px; border: 1px solid #111; font-size: 10px; text-transform: uppercase; letter-spacing: .08em; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 4px 24px; margin: 12px 0; }
  .f { display: flex; gap: 8px; border-bottom: 1px dotted #bbb; padding: 3px 0; }
  .f dt { min-width: 118px; color: #555; text-transform: uppercase; font-size: 10px; letter-spacing: .05em; padding-top: 2px; }
  .f dd { margin: 0; font-weight: 600; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; }
  th, td { border: 1px solid #999; padding: 5px 7px; text-align: left; font-size: 11px; }
  th { background: #eee; text-transform: uppercase; font-size: 10px; letter-spacing: .05em; }
  td.n { text-align: right; font-variant-numeric: tabular-nums; }
  .returns { margin-top: 10px; border: 2px solid #111; padding: 8px 10px; background: #f6f6f6; }
  .returns h3 { margin: 0 0 4px; font-size: 11px; text-transform: uppercase; letter-spacing: .08em; }
  .sigs { display: grid; grid-template-columns: repeat(3, 1fr); gap: 18px; margin-top: 18px; }
  .sig { border-top: 1px solid #111; padding-top: 4px; font-size: 10px; text-transform: uppercase; letter-spacing: .05em; color: #444; }
  .sig strong { display: block; font-size: 11px; color: #111; text-transform: none; letter-spacing: 0; margin-bottom: 14px; }
  .verify { margin-top: 14px; text-align: center; }
  .verify svg { max-width: 100%; height: auto; }
  .token { font-family: "SFMono-Regular", Consolas, monospace; font-size: 11px; letter-spacing: .12em; margin-top: 2px; }
  .hint { font-size: 9px; color: #666; margin-top: 2px; }
  footer { margin-top: 12px; border-top: 1px solid #999; padding-top: 6px; font-size: 9px; color: #666; display: flex; justify-content: space-between; }
  .draft { background: #fff3cd; border: 2px solid #856404; color: #856404; padding: 6px 10px; font-weight: 700; text-align: center; margin-bottom: 10px; text-transform: uppercase; letter-spacing: .08em; }
  @media print { body { padding: 0; } .sheet { border: none; } }
</style></head><body>
<div class="sheet">
{{if not .SlipNo}}<div class="draft">Draft — not authorised — not valid at the gate</div>{{end}}
<header>
  <div>
    <div class="org">{{.OrgName}}</div>
    <div class="title">{{.Title}}</div>
  </div>
  <div style="text-align:right">
    <div class="no">{{.SlipNoStr}}</div>
    <div class="status">{{.Status}}</div>
  </div>
</header>

<div class="grid">
  <dl class="f"><dt>Issued to</dt><dd>{{dash .IssuedToName}}</dd></dl>
  <dl class="f"><dt>Department</dt><dd>{{dash .Dept}}</dd></dl>
  <dl class="f"><dt>Purpose</dt><dd>{{dash .Purpose}}</dd></dl>
  <dl class="f"><dt>Facility</dt><dd>{{dash .FacilityName}}</dd></dl>
{{if .IsCargo}}
  <dl class="f"><dt>Driver</dt><dd>{{dash .DriverName}}</dd></dl>
  <dl class="f"><dt>Driver ID</dt><dd>{{dash .DriverIDNo}}</dd></dl>
  <dl class="f"><dt>Vehicle reg</dt><dd>{{dash .VehicleReg}}</dd></dl>
  <dl class="f"><dt>Transporter</dt><dd>{{dash .Transporter}}</dd></dl>
  <dl class="f"><dt>Destination</dt><dd>{{dash .Destination}}</dd></dl>
{{else}}
  <dl class="f"><dt>Released by</dt><dd>{{dash .FromCustodian}}</dd></dl>
  <dl class="f"><dt>Received by</dt><dd>{{dash .ToCustodian}}</dd></dl>
{{end}}
  <dl class="f"><dt>Authorised by</dt><dd>{{dash .AuthorizedName}}</dd></dl>
  <dl class="f"><dt>Authorised at</dt><dd>{{datetime .AuthorizedAt}}</dd></dl>
</div>

<table>
  <thead><tr><th style="width:44%">Description</th><th>Item / Asset</th><th>Serial</th><th class="n">Qty</th><th>Unit</th><th>Condition out</th></tr></thead>
  <tbody>
  {{range .Lines}}
    <tr>
      <td>{{.Description}}</td>
      <td>{{if .AssetTag}}{{.AssetTag}}{{else}}{{dash .ItemSKU}}{{end}}</td>
      <td>{{dash .SerialNo}}</td>
      <td class="n">{{qty .Qty}}</td>
      <td>{{.UOM}}</td>
      <td>{{dash .ConditionOut}}</td>
    </tr>
  {{else}}
    <tr><td colspan="6" style="text-align:center;color:#777">No items listed</td></tr>
  {{end}}
  </tbody>
</table>

{{if .Returnable}}
<div class="returns">
  <h3>Returnable — must be brought back</h3>
  <div>Return by <strong>{{date .ReturnBy}}</strong>{{if .ReturnedAt}} — returned {{datetime .ReturnedAt}}{{else}} — <strong>OUTSTANDING</strong>{{end}}</div>
</div>
{{end}}

{{if .Barcode}}
<div class="verify">
  {{svg .Barcode}}
  <div class="token">{{.VerifyToken}}</div>
  {{if .VerifyURL}}<div class="hint">Verify at {{.VerifyURL}}</div>{{end}}
  <div class="hint">Security: scan or key this token before releasing the vehicle. Do not accept this slip if it does not resolve.</div>
</div>
{{end}}

<div class="sigs">
  <div class="sig"><strong>&nbsp;</strong>Storekeeper</div>
  <div class="sig"><strong>&nbsp;</strong>{{if .IsCargo}}Driver{{else}}Receiving custodian{{end}}</div>
  <div class="sig"><strong>&nbsp;</strong>Security / gate</div>
</div>

<footer>
  <span>{{.OrgName}} — stores</span>
  <span>Printed {{.PrintedAt}}</span>
</footer>
</div>
</body></html>`
